// Generated by BUCKLESCRIPT VERSION 1.7.3, PLEASE EDIT WITH CARE
'use strict';

var Curry    = require("bs-platform/lib/js/curry.js");
var Synth    = require("./synth.js");
var React    = require("react");
var ReactRe  = require("reason-react/lib/js/src/reactRe.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var include = ReactRe.Component[/* Stateful */8];

var componentDidMount = include[0];

var componentWillUpdate = include[1];

var componentDidUpdate = include[2];

var componentWillReceiveProps = include[3];

var componentWillUnmount = include[4];

var getInstanceVars = include[5];

var jsPropsToReasonProps = include[6];

function max(a, b) {
  var match = Caml_obj.caml_greaterthan(a, b);
  if (match !== 0) {
    return a;
  } else {
    return b;
  }
}

function getInitialState() {
  return /* record */[
          /* color */"yellow",
          /* x */0,
          /* y */1
        ];
}

var name = "Page";

function handleMouseMove(_, $$event) {
  var x = $$event.pageX;
  var y = $$event.pageY;
  var match = +(y > 350);
  return /* Some */[/* record */[
            /* color */match !== 0 ? "blue" : "yellow",
            /* x */x,
            /* y */max(y, 700)
          ]];
}

function render(param) {
  return React.createElement("div", {
              style: {
                background: param[/* state */0][/* color */0],
                bottom: "0",
                left: "0",
                position: "absolute",
                right: "0",
                top: "0"
              },
              onMouseMove: Curry._1(param[/* updater */2], handleMouseMove)
            }, param[/* props */1][/* message */0]);
}

var Page_014 = /* JsProps */include[7];

var Page_015 = /* InstanceVars */include[8];

var Page = /* module */[
  /* Synth */Synth.Synth,
  /* audioCtx */Synth.audioCtx,
  /* start */Synth.start,
  /* spn */Synth.spn,
  /* schedule */Synth.schedule,
  /* main */Synth.main,
  /* f */Synth.f,
  /* componentDidMount */componentDidMount,
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  Page_014,
  Page_015,
  /* max */max,
  /* screenHeight */700,
  /* getInitialState */getInitialState,
  /* name */name,
  /* handleMouseMove */handleMouseMove,
  /* render */render
];

var include$1 = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include$1[1];

function createElement(message) {
  return Curry._1(wrapProps, /* record */[/* message */message]);
}

var comp = include$1[0];

exports.Page          = Page;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* include Not a pure module */
